//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoTest()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Code_test { get; set; }
        public string Title_test { get; set; }
        public string Importance_test { get; set; }
        public string Duration_test { get; set; }
        public string Descriptions { get; set; }
        public int Code_rezult { get; set; }
    
        public virtual Rezults Rezults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public override string ToString() => Title_test;
    }
}
