//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutotestsEntities : DbContext
    {
        public AutotestsEntities()
            : base("name=AutotestsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoTest> AutoTest { get; set; }
        public virtual DbSet<Client_individual> Client_individual { get; set; }
        public virtual DbSet<Client_organization> Client_organization { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Rezults> Rezults { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
