//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Code_order { get; set; }
        public int Code_worker { get; set; }
        public Nullable<int> Code_client_ind { get; set; }
        public Nullable<int> Code_client_org { get; set; }
        public int Code_Autotest { get; set; }
        public System.DateTime Registration_date { get; set; }
    
        public virtual AutoTest AutoTest { get; set; }
        public virtual Client_individual Client_individual { get; set; }
        public virtual Client_organization Client_organization { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
